### ISSUE TITLE
Bug: It's not usable

### ISSUE THREAD

**Issue by KenMizz** [Dream-Block/Util.js#1]
I'm trying to use this by it's not working
any solution?

**Comment by Subilan** [comment]
Wow you are so fast :laughing: 
It's a **brand new** repository and it only has one function now!
You can contribute to it if you like. We use ![](https://img.shields.io/badge/lang-TypeScript-blue) yes!

**Comment by Subilan** [comment]
So... if you have any question please comment here and I'll help you.\
~~**TYPESCRIPT IS SO FREAKING DIFFICULT! TERRIBLE TYPES IS JUST LIKE A HORRIBLE DREAM!!!!!!!!!!**~~

**Comment by KenMizz** [comment]
@Subilan thank you for answering, I saw your commit. I think I'm fine now, thank you very much 💃
